// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZwc1Qdne5LGjydzpVrfUiFc5c7rWBqf0',
    appId: '1:351305965658:web:6461519b434fe44533f863',
    messagingSenderId: '351305965658',
    projectId: 'mlkit-a9cf1',
    authDomain: 'mlkit-a9cf1.firebaseapp.com',
    storageBucket: 'mlkit-a9cf1.firebasestorage.app',
    measurementId: 'G-XRQ6FL0XF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQICLb7reyPnMr5hra6z5wNAS-VkxCLJU',
    appId: '1:351305965658:android:574facef4f10efb133f863',
    messagingSenderId: '351305965658',
    projectId: 'mlkit-a9cf1',
    storageBucket: 'mlkit-a9cf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-3x8Bk7MGZoGxdJGMNbmi7JGqAANQAc',
    appId: '1:351305965658:ios:29e529ef6494d31b33f863',
    messagingSenderId: '351305965658',
    projectId: 'mlkit-a9cf1',
    storageBucket: 'mlkit-a9cf1.firebasestorage.app',
    iosBundleId: 'com.example.mlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU-3x8Bk7MGZoGxdJGMNbmi7JGqAANQAc',
    appId: '1:351305965658:ios:29e529ef6494d31b33f863',
    messagingSenderId: '351305965658',
    projectId: 'mlkit-a9cf1',
    storageBucket: 'mlkit-a9cf1.firebasestorage.app',
    iosBundleId: 'com.example.mlkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZwc1Qdne5LGjydzpVrfUiFc5c7rWBqf0',
    appId: '1:351305965658:web:305cf029ec58b6d433f863',
    messagingSenderId: '351305965658',
    projectId: 'mlkit-a9cf1',
    authDomain: 'mlkit-a9cf1.firebaseapp.com',
    storageBucket: 'mlkit-a9cf1.firebasestorage.app',
    measurementId: 'G-3P6LTZRQD3',
  );
}
